name: Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:
  
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - id: version_bump
        name: Bump version and push tag
        if: github.ref == 'refs/heads/main'
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          
      - name: Login to Azure via Azure-CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Retrieve Azure Container Registry credentials
        run: |
           az acr login -n oechsler
           
      - name: Build Docker image
        if: github.ref != 'refs/heads/main'
        run: |
          docker build . -t snug:latest
          
      - name: Build and publish Docker image
        if: github.ref == 'refs/heads/main'
        uses: mr-smithers-excellent/docker-build-push@v5.2
        with:
          image: snug
          tags: latest, ${{ steps.version_bump.outputs.new_tag }}
          registry: oechsler.azurecr.io
